auto-import changelog data from bind-9.2.4rc7-7.src.rpm Thu Aug 19 2004 Jason Vas Dias <jvdias@redhat.com> - Upgrade to bind-9.2.4rc7; applied initscript fix - for bug 102035.

diff --git a/named.init b/named.init
--- a/named.init
+++ b/named.init
@@ -37,8 +37,25 @@ start() {
 	if [ -n "${ROOTDIR}" -a "x${ROOTDIR}" != "x/" ]; then
 		OPTIONS="${OPTIONS} -t ${ROOTDIR}"
 	fi
-	daemon /usr/sbin/named -u named ${OPTIONS}
-	RETVAL=$?
+        conf_ok=0;
+	if [ -x /usr/sbin/named-checkconf ] && /usr/sbin/named-checkconf; then
+           conf_ok=1;
+        else
+	   RETVAL=$?;
+	fi
+	if [ $conf_ok -eq 1 ]; then	   
+	   daemon /usr/sbin/named -u named ${OPTIONS};
+	   RETVAL=$?;
+	else
+	   named_err=`/usr/sbin/named -g 2>&1 | sed s/\n/\\n/g`;
+	   if [ `tty` != "/dev/console" ]; then
+	       echo -e "\n$named_err";
+	       echo -n  "Error in configuration file /etc/named.conf : ";
+	   fi;
+           failure $"Error in configuration file /etc/named.conf : $named_err";
+           echo
+           return $RETVAL;
+        fi;
  	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/named 
         echo
 	return $RETVAL
